version: '2'
services:
    notification-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/notification/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=notification
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
